development:
  adapter: postgresql
  encoding: unicode
  database: alpha_blog
  pool: 5
  username: app
  password: app

test:
  adapter: postgresql
  encoding: unicode
  database: alpha_blog_test
  pool: 5
  username: app
  password: app